### ISSUE TITLE
Уязвимость SQL Injection

### ISSUE THREAD

**Issue by JungleTryne** [SayHelloRoman/social_network#1]
Я решил глянуть код, и увидел очень большую дыру:

```Python3
cursor.execute(f"SELECT id, pasword, status FROM users WHERE id = '{name}'")
```

Переменная `name` напрямую подставляется в SQL запрос. Я этим и воспользовался, чтобы взломать пользователя.

Как я это сделал:
1) Создал пользователя admin с большим паролем, который сложно подобрать
2) Создал пользователя dummy с паролем 11111qqqqq -- чтобы при сортировке паролей всех пользователей
он оказался первым в списке
3) Подал запрос на сервер об авторизации вида
` curl -d "nick=admin' or '1'='1' order by pasword --&password=11111qqqqq" -X POST  http://127.0.0.1:8888/sing_in `
На сервере такой запрос превращается в
` SELECT id, pasword, status FROM users WHERE id = 'admin' or '1'='1' order by pasword -- ' `
`'1' = '1'` позволяет мне вывести всех пользователей, а `order by pasword` -- сортирует по паролям.
4) В итоге в коде 
```Python3
elif r[0][1] != password:
```
берется самый первый пароль из таблицы для проверки. А его я знаю -- `11111qqqqq`. Он совпадает с тем, который я отправил на сервер, несмотря на то, что это не пароль пользователя `admin`, но я в итоге захожу как админ

Как исправить?
- Не хранить пароли в прямом виде. Их надо хэшировать
- Не подставлять input пользователя напрямую в запрос, а предварительно обрабатывать

**Comment by SayHelloRoman** [comment]
Так вышло что это учебный проект, который был написанный 4 месяца назад. Я попытаюсь исправить данную проблему в скором времени. В будущих проектах я буду знать об этой уязвимости и обезательно исправлю её. Спасибо, что сообщили.
